
services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-pgtap
      - postgresql-9.5-postgis-2.3

before_install:
  - sudo apt-get install libtap-parser-sourcehandler-pgtap-perl

before_script:
  - psql -U postgres -c 'CREATE DATABASE travis_ci_test;' -U postgres

script:
  - pg_prove -U postgres -d travis_ci_test tests/
