
matrix:
  include:

    - env: BUILD=docs
      language: python
      before_install: []
      install:
        - pip install Sphinx sphinx_rtd_theme
        - pip install -r requirements-docs.txt
      before_script: []
      script: sphinx-build -b html db/docs/source db/docs
      after_script: []

    - env: BUILD=db PGSQL=9.4 PGIS=2.3 PGPORT=5432
      addons:
        postgresql: 9.4
        apt:
          packages:
            - postgresql-9.4
            - postgresql-9.4-pgtap

    - env: BUILD=db PGSQL=9.5 PGIS=2.3 PGPORT=5432
      addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-9.5
            - postgresql-9.5-pgtap

    - env: BUILD=db PGSQL=9.5 PGIS=2.4 PGPORT=5432
      addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-9.5
            - postgresql-9.5-pgtap

    - env: BUILD=db PGSQL=9.6 PGIS=2.3 PGPORT=5432
      addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-9.6
            - postgresql-9.6-pgtap

    - env: BUILD=db PGSQL=9.6 PGIS=2.4 PGPORT=5432
      addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-9.6
            - postgresql-9.6-pgtap

    - env: BUILD=db PGSQL=10 PGIS=2.4 PGPORT=5433
      addons:
        postgresql: 10
        apt:
          packages:
            - postgresql-10
            - postgresql-10-pgtap

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libtap-parser-sourcehandler-pgtap-perl
  - sudo apt-get install -y postgresql-${PGSQL}-postgis-${PGIS}

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - export PGPASSWORD=travis
  - psql -U travis -c 'CREATE DATABASE nz_buildings_travis_db;'
  - sudo make install
  - nz-buildings-load nz_buildings_travis_db --with-test-data

script:
  - pg_prove -U travis -d nz_buildings_travis_db db/tests/
