
matrix:
  include:

    - addons:
        postgresql: 9.4
        apt:
          packages:
            - postgresql-9.4
            - postgresql-9.4-pgtap
            - postgresql-9.4-postgis-2.3

    - addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-9.5
            - postgresql-9.5-pgtap
            - postgresql-9.5-postgis-2.3

    - addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-9.6
            - postgresql-9.6-pgtap
            - postgresql-9.6-postgis-2.3

before_install:
  - sudo apt-get install libtap-parser-sourcehandler-pgtap-perl

before_script:
  - export PGPASSWORD=
  - psql -U postgres -c 'CREATE DATABASE nz_buildings_travis_db;'
  - sudo make install
  - nz-buildings-load nz_buildings_travis_db --with-test-data

script:
  - pg_prove -U postgres -d nz_buildings_travis_db tests/
