
services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-pgtap
      - postgresql-9.5-postgis-2.3

before_install:
  - sudo apt-get install libtap-parser-sourcehandler-pgtap-perl

before_script:
  - export PGPASSWORD=
  - sudo -E make install
  - psql -U postgres -c 'CREATE DATABASE nz_buildings_travis_db;' -U postgres
  - nz-buildings-load nz_buildings_travis_db

script:
  - pg_prove -U postgres -d nz_buildings_travis_db tests/
